# Market Basket Analysis

In [32]:
import numpy as np 
import pandas as pd 

import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))
       
import warnings
warnings.filterwarnings("ignore")        

        

from mlxtend.frequent_patterns import apriori
from mlxtend.frequent_patterns import association_rules

/kaggle/input/datasets-for-appiori/basket_analysis.csv

In [33]:
df = pd.read_csv('/kaggle/input/datasets-for-appiori/basket_analysis.csv')

df.head()

,Unnamed: 0,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True
3,3,False,False,True,True,False,True,False,False,False,True,True,True,False,False,False,False
4,4,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

#  Data Preparation

In [34]:
df.drop('Unnamed: 0',axis=1,inplace=True)
df.head()

,Apple,Bread,Butter,Cheese,Corn,Dill,Eggs,Ice cream,Kidney Beans,Milk,Nutmeg,Onion,Sugar,Unicorn,Yogurt,chocolate
0,False,True,False,False,True,True,False,True,False,False,False,False,True,False,True,True
1,False,False,False,False,False,False,False,False,False,True,False,False,False,False,False,False
2,True,False,True,False,False,True,False,True,False,True,False,False,False,False,True,True
3,False,False,True,True,False,True,False,False,False,True,True,True,False,False,False,False
4,True,True,False,False,False,False,False,False,False,False,False,False,False,False,False,False

In [35]:
df.shape

(999, 16)

In [36]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 999 entries, 0 to 998
Data columns (total 16 columns):
 #   Column        Non-Null Count  Dtype
---  ------        --------------  -----
 0   Apple         999 non-null    bool
 1   Bread         999 non-null    bool
 2   Butter        999 non-null    bool
 3   Cheese        999 non-null    bool
 4   Corn          999 non-null    bool
 5   Dill          999 non-null    bool
 6   Eggs          999 non-null    bool
 7   Ice cream     999 non-null    bool
 8   Kidney Beans  999 non-null    bool
 9   Milk          999 non-null    bool
 10  Nutmeg        999 non-null    bool
 11  Onion         999 non-null    bool
 12  Sugar         999 non-null    bool
 13  Unicorn       999 non-null    bool
 14  Yogurt        999 non-null    bool
 15  chocolate     999 non-null    bool
dtypes: bool(16)
memory usage: 15.7 KB

In [37]:
df.mean()

Apple           0.383383
Bread           0.384384
Butter          0.420420
Cheese          0.404404
Corn            0.407407
Dill            0.398398
Eggs            0.384384
Ice cream       0.410410
Kidney Beans    0.408408
Milk            0.405405
Nutmeg          0.401401
Onion           0.403403
Sugar           0.409409
Unicorn         0.389389
Yogurt          0.420420
chocolate       0.421421
dtype: float64

In [38]:
apriori(df, min_support=0.15)[1:25]

     support itemsets
1   0.384384      (1)
2   0.420420      (2)
3   0.404404      (3)
4   0.407407      (4)
5   0.398398      (5)
6   0.384384      (6)
7   0.410410      (7)
8   0.408408      (8)
9   0.405405      (9)
10  0.401401     (10)
11  0.403403     (11)
12  0.409409     (12)
13  0.389389     (13)
14  0.420420     (14)
15  0.421421     (15)
16  0.154154   (0, 1)
17  0.188188   (0, 2)
18  0.162162   (0, 3)
19  0.186186   (0, 4)
20  0.179179   (0, 5)
21  0.156156   (0, 6)
22  0.172172   (0, 7)
23  0.176176   (0, 8)
24  0.184184   (0, 9)

In [39]:
apriori(df, min_support=0.15, use_colnames=True)[1:25]

     support               itemsets
1   0.384384                (Bread)
2   0.420420               (Butter)
3   0.404404               (Cheese)
4   0.407407                 (Corn)
5   0.398398                 (Dill)
6   0.384384                 (Eggs)
7   0.410410            (Ice cream)
8   0.408408         (Kidney Beans)
9   0.405405                 (Milk)
10  0.401401               (Nutmeg)
11  0.403403                (Onion)
12  0.409409                (Sugar)
13  0.389389              (Unicorn)
14  0.420420               (Yogurt)
15  0.421421            (chocolate)
16  0.154154         (Apple, Bread)
17  0.188188        (Apple, Butter)
18  0.162162        (Apple, Cheese)
19  0.186186          (Apple, Corn)
20  0.179179          (Apple, Dill)
21  0.156156          (Apple, Eggs)
22  0.172172     (Apple, Ice cream)
23  0.176176  (Apple, Kidney Beans)
24  0.184184          (Apple, Milk)

#  Modeling

In [40]:
frequent_itemsets = apriori(df,
                            min_support = .006,
                            max_len = 3,
                            use_colnames = True)

In [41]:
frequent_itemsets

      support                      itemsets
0    0.383383                       (Apple)
1    0.384384                       (Bread)
2    0.420420                      (Butter)
3    0.404404                      (Cheese)
4    0.407407                        (Corn)
..        ...                           ...
691  0.098098    (Onion, Yogurt, chocolate)
692  0.087087      (Sugar, Yogurt, Unicorn)
693  0.090090   (Sugar, chocolate, Unicorn)
694  0.095095    (Sugar, Yogurt, chocolate)
695  0.086086  (Unicorn, Yogurt, chocolate)

[696 rows x 2 columns]

In [46]:
rules = association_rules(frequent_itemsets,
                            metric = 'support',
                            min_threshold=0.1)

In [47]:
rules

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
0,(Apple),(Bread),0.383383,0.384384,0.154154,0.402089,1.046059,0.006788,1.029610
1,(Bread),(Apple),0.384384,0.383383,0.154154,0.401042,1.046059,0.006788,1.029482
2,(Apple),(Butter),0.383383,0.420420,0.188188,0.490862,1.167549,0.027006,1.138354
3,(Butter),(Apple),0.420420,0.383383,0.188188,0.447619,1.167549,0.027006,1.116289
4,(Apple),(Cheese),0.383383,0.404404,0.162162,0.422977,1.045925,0.007120,1.032186
...,...,...,...,...,...,...,...,...,...
433,"(Milk, Yogurt)",(chocolate),0.190190,0.421421,0.104104,0.547368,1.298862,0.023954,1.278255
434,"(chocolate, Yogurt)",(Milk),0.198198,0.405405,0.104104,0.525253,1.295623,0.023753,1.252444
435,(Milk),"(chocolate, Yogurt)",0.405405,0.198198,0.104104,0.256790,1.295623,0.023753,1.078836
436,(chocolate),"(Milk, Yogurt)",0.421421,0.190190,0.104104,0.247031,1.298862,0.023954,1.075489
437,(Yogurt),"(Milk, chocolate)",0.420420,0.211211,0.104104,0.247619,1.172376,0.015307,1.048390

In [48]:
filtered_rules = rules[(rules['antecedent support'] > 0.02)&
                        (rules['consequent support'] >0.01) &
                        (rules['confidence'] > 0.2) &
                        (rules['lift'] > 1.0)]

In [49]:
rules2 = association_rules(frequent_itemsets, metric="lift", min_threshold=1)
rules2 = rules2.sort_values(['lift'], ascending=False)
rules2.head()

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
1969,"(Dill, Cheese)",(Onion),0.177177,0.403403,0.102102,0.576271,1.428523,0.030628,1.407968
1972,(Onion),"(Dill, Cheese)",0.403403,0.177177,0.102102,0.253102,1.428523,0.030628,1.101653
2843,"(Unicorn, Dill)",(chocolate),0.168168,0.421421,0.101101,0.601190,1.426578,0.030231,1.450764
2846,(chocolate),"(Unicorn, Dill)",0.421421,0.168168,0.101101,0.239905,1.426578,0.030231,1.094379
2763,(chocolate),"(Dill, Milk)",0.421421,0.190190,0.114114,0.270784,1.423753,0.033964,1.110521

In [50]:
filtered_rules.sort_values('support',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
208,(Milk),(chocolate),0.405405,0.421421,0.211211,0.520988,1.236263,0.040365,1.207857
209,(chocolate),(Milk),0.421421,0.405405,0.211211,0.501188,1.236263,0.040365,1.192021
66,(Ice cream),(Butter),0.410410,0.420420,0.207207,0.504878,1.200889,0.034662,1.170579
67,(Butter),(Ice cream),0.420420,0.410410,0.207207,0.492857,1.200889,0.034662,1.162571
182,(Ice cream),(chocolate),0.410410,0.421421,0.202202,0.492683,1.169098,0.029246,1.140467
...,...,...,...,...,...,...,...,...,...
372,"(chocolate, Corn)",(Kidney Beans),0.192192,0.408408,0.100100,0.520833,1.275276,0.021607,1.234626
373,"(Corn, Kidney Beans)",(chocolate),0.195195,0.421421,0.100100,0.512821,1.216883,0.017841,1.187609
374,"(chocolate, Kidney Beans)",(Corn),0.191191,0.407407,0.100100,0.523560,1.285102,0.022207,1.243793
375,(Corn),"(chocolate, Kidney Beans)",0.407407,0.191191,0.100100,0.245700,1.285102,0.022207,1.072264
366,"(Yogurt, Corn)",(Kidney Beans),0.190190,0.408408,0.100100,0.526316,1.288700,0.022425,1.248916

In [51]:
filtered_rules.sort_values('confidence',ascending=False)

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
403,"(Unicorn, Dill)",(chocolate),0.168168,0.421421,0.101101,0.601190,1.426578,0.030231,1.450764
390,"(Dill, Milk)",(chocolate),0.190190,0.421421,0.114114,0.600000,1.423753,0.033964,1.446446
325,"(Dill, Cheese)",(Onion),0.177177,0.403403,0.102102,0.576271,1.428523,0.030628,1.407968
391,"(Dill, chocolate)",(Milk),0.199199,0.405405,0.114114,0.572864,1.413065,0.033358,1.392051
258,"(Ice cream, Kidney Beans)",(Butter),0.196196,0.420420,0.110110,0.561224,1.334913,0.027625,1.320902
...,...,...,...,...,...,...,...,...,...
287,(Butter),"(Unicorn, Ice cream)",0.420420,0.185185,0.100100,0.238095,1.285714,0.022244,1.069444
370,(Yogurt),"(Corn, Kidney Beans)",0.420420,0.195195,0.100100,0.238095,1.219780,0.018036,1.056306
321,(Yogurt),"(Butter, Nutmeg)",0.420420,0.198198,0.100100,0.238095,1.201299,0.016774,1.052365
322,(Butter),"(Yogurt, Nutmeg)",0.420420,0.192192,0.100100,0.238095,1.238839,0.019299,1.060248
376,(chocolate),"(Corn, Kidney Beans)",0.421421,0.195195,0.100100,0.237530,1.216883,0.017841,1.055523

In [52]:
filtered_rules2 = rules[(rules['antecedent support'] > 0.02)&
                        (rules['consequent support'] >0.01) &
                        (rules['confidence'] > 0.45) &
                        (rules['lift'] > 1.0)&
                        (rules['support']>0.195)]
filtered_rules2

,antecedents,consequents,antecedent support,consequent support,support,confidence,lift,leverage,conviction
66,(Ice cream),(Butter),0.410410,0.420420,0.207207,0.504878,1.200889,0.034662,1.170579
67,(Butter),(Ice cream),0.420420,0.410410,0.207207,0.492857,1.200889,0.034662,1.162571
68,(Kidney Beans),(Butter),0.408408,0.420420,0.202202,0.495098,1.177626,0.030499,1.147905
69,(Butter),(Kidney Beans),0.420420,0.408408,0.202202,0.480952,1.177626,0.030499,1.139764
70,(Milk),(Butter),0.405405,0.420420,0.198198,0.488889,1.162857,0.027757,1.133960
71,(Butter),(Milk),0.420420,0.405405,0.198198,0.471429,1.162857,0.027757,1.124909
72,(Butter),(Nutmeg),0.420420,0.401401,0.198198,0.471429,1.174457,0.029441,1.132484
73,(Nutmeg),(Butter),0.401401,0.420420,0.198198,0.493766,1.174457,0.029441,1.144884
74,(Onion),(Butter),0.403403,0.420420,0.197197,0.488834,1.162726,0.027598,1.133838
75,(Butter),(Onion),0.420420,0.403403,0.197197,0.469048,1.162726,0.027598,1.123635
76,(Sugar),(Butter),0.409409,0.420420,0.196196,0.479218,1.139853,0.024072,1.112902
77,(Butter),(Sugar),0.420420,0.409409,0.196196,0.466667,1.139853,0.024072,1.107357
82,(chocolate),(Butter),0.421421,0.420420,0.202202,0.479810,1.141262,0.025028,1.114169
83,(Butter),(chocolate),0.420420,0.421421,0.202202,0.480952,1.141262,0.025028,1.114693
92,(Cheese),(Kidney Beans),0.404404,0.408408,0.200200,0.495050,1.212143,0.035038,1.171583
93,(Kidney Beans),(Cheese),0.408408,0.404404,0.200200,0.490196,1.212143,0.035038,1.168284
114,(Corn),(Kidney Beans),0.407407,0.408408,0.195195,0.479115,1.173128,0.028807,1.135744
115,(Kidney Beans),(Corn),0.408408,0.407407,0.195195,0.477941,1.173128,0.028807,1.135107
148,(Dill),(chocolate),0.398398,0.421421,0.199199,0.500000,1.186461,0.031306,1.157157
149,(chocolate),(Dill),0.421421,0.398398,0.199199,0.472684,1.186461,0.031306,1.140875
168,(Ice cream),(Kidney Beans),0.410410,0.408408,0.196196,0.478049,1.170516,0.028581,1.133423
169,(Kidney Beans),(Ice cream),0.408408,0.410410,0.196196,0.480392,1.170516,0.028581,1.134682
176,(Sugar),(Ice cream),0.409409,0.410410,0.195195,0.476773,1.161697,0.027169,1.126832
177,(Ice cream),(Sugar),0.410410,0.409409,0.195195,0.475610,1.161697,0.027169,1.126243
182,(Ice cream),(chocolate),0.410410,0.421421,0.202202,0.492683,1.169098,0.029246,1.140467
183,(chocolate),(Ice cream),0.421421,0.410410,0.202202,0.479810,1.169098,0.029246,1.133412
184,(Milk),(Kidney Beans),0.405405,0.408408,0.199199,0.491358,1.203105,0.033628,1.163081
185,(Kidney Beans),(Milk),0.408408,0.405405,0.199199,0.487745,1.203105,0.033628,1.160740
208,(Milk),(chocolate),0.405405,0.421421,0.211211,0.520988,1.236263,0.040365,1.207857
209,(chocolate),(Milk),0.421421,0.405405,0.211211,0.501188,1.236263,0.040365,1.192021
210,(Onion),(Nutmeg),0.403403,0.401401,0.195195,0.483871,1.205454,0.033269,1.159785
211,(Nutmeg),(Onion),0.401401,0.403403,0.195195,0.486284,1.205454,0.033269,1.161336
226,(Onion),(chocolate),0.403403,0.421421,0.196196,0.486352,1.154076,0.026193,1.126411
227,(chocolate),(Onion),0.421421,0.403403,0.196196,0.465558,1.154076,0.026193,1.116299
238,(Yogurt),(chocolate),0.420420,0.421421,0.198198,0.471429,1.118663,0.021024,1.094608
239,(chocolate),(Yogurt),0.421421,0.420420,0.198198,0.470309,1.118663,0.021024,1.094184